---
  os: osx
  language: node_js
  osx_image: xcode10.1
  node_js:
    - node
    - lts/*
  cache:
    directories:
      - "~/.npm"
  before_install:
    - gem update --system
    - echo -e "machine github.com\n  login $APPLE_USERNAME\n  password $CI_USER_PASSWORD" >> ~/.netrc
  before_script:
    - bundle update
    - bundle install
    - npm i -g npm@latest
  script:
    - npm ci
    - npx jest --ci
